name: Vue3 CI/CD

on:
  push:
    branches: [main]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Install Dependencies
      run: npm install

    - name: Build
      run: npm run build

    - name: Archive Production Artifact
      uses: actions/upload-artifact@v2
      with:
        name: dist
        path: dist

  deploy:

    needs: build

    runs-on: ubuntu-latest

    steps:

    - name: Download Artifact
      uses: actions/download-artifact@v2
      with:
        name: dist
        path: dist

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        deploy_key: ${{ secrets.ACTIONS_DEPLOY_KEY }}
        publish_dir: ./dist